# 参考文档：https://decapcms.org/docs/configuration-options/
backend:
  name: github
  branch: main # 改为你的分支
  repo: IsSmallPigPig/New_Blog_Astro # 改为你的仓库
  site_domain: ankoqaq.netlify.app # 改为你的域名
  base_url: https://ankoqaq.netlify.app # 改为你的URL
  auth_endpoint: oauth 


collections:
  - name: "blog"
    label: "博客文章"
    folder: "src/content/posts/"
    create: true
    slug: "{{fields.filename}}"  # 使用自定义字段作为文件名
    fields:
      - { label: "文件名", name: "filename", widget: "string", required: true }  # 新增文件名字段
      - { label: "标题", name: "title", widget: "string" }
      - { label: "简介", name: "description", widget: "string", default: "这是一篇有意思的文章" }
      - { label: "发布日期", name: "pubDate", widget: "datetime", date_format: "YYYY-MM-DD" }
      - { label: "更新日期", name: "updatedDate", widget: "datetime", date_format: "YYYY-MM-DD" }
      - { label: "标签", name: "tags", widget: "list" }
      - { label: "封面", name: "cover", widget: "string", default: "/social-card.avif" }
      - { label: "正文", name: "body", widget: "markdown" }

  - name: "moments"
    label: "闲言碎语"
    folder: "src/content/moments/"
    create: true
    slug: "{{fields.filename}}"  # 使用自定义字段作为文件名
    fields:
      - { label: "文件名", name: "filename", widget: "string", required: true }  # 新增文件名字段
      - { label: "标题", name: "mood", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime", date_format: "YYYY-MM-DD" }
      - { label: "标签", name: "tags", widget: "list" }
      - { label: "正文", name: "body", widget: "markdown" }